version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: 'bitnami/redis:6.2.3'
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_PORT_NUMBER=7777
    ports:
      - '7777:7777'
